# Generated by Django 5.2.8 on 2025-12-07 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='actual_end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Actual consultation end time'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='actual_start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Actual consultation start time'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='cancellation_reason',
            field=models.TextField(blank=True, verbose_name='Reason for cancellation'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Marked as completed on'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='completed_by_doctor',
            field=models.BooleanField(default=False, verbose_name='Marked as completed by doctor'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='consultation_duration',
            field=models.PositiveIntegerField(default=0, verbose_name='Consultation duration (minutes)'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor_notes',
            field=models.TextField(blank=True, verbose_name='Doctor notes after consultation'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='follow_up_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='follow_up_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='follow_up_required',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AppointmentNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('doctor', 'Doctor Note'), ('patient', 'Patient Note'), ('system', 'System Note'), ('follow_up', 'Follow-up Note')], max_length=20)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='appointment.appointment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentRescheduleHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_date', models.DateTimeField()),
                ('new_date', models.DateTimeField()),
                ('reason', models.TextField(blank=True)),
                ('rescheduled_by', models.CharField(choices=[('doctor', 'Doctor'), ('patient', 'Patient'), ('system', 'System')], max_length=20)),
                ('rescheduled_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reschedule_history', to='appointment.appointment')),
            ],
            options={
                'verbose_name_plural': 'Appointment reschedule history',
                'ordering': ['-rescheduled_at'],
            },
        ),
    ]
