# Generated by Django 5.2.8 on 2025-12-21 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_alter_exporthistory_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
