# Generated by Django 5.2.8 on 2025-11-09 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_alter_symptom_symptom_image'),
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='departments',
            field=models.ManyToManyField(blank=True, through='doctor.DoctorSpecializationDepartment', to='adminapp.department'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='symptoms',
            field=models.ManyToManyField(blank=True, through='doctor.DoctorSpecializationSymptom', to='adminapp.symptom'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminapp.district'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminapp.division'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='total_experience',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='upazila',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminapp.upazila'),
        ),
        migrations.AlterField(
            model_name='doctorspecializationdepartment',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.department'),
        ),
        migrations.AlterField(
            model_name='doctorspecializationsymptom',
            name='symptom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.symptom'),
        ),
    ]
