# Generated by Django 5.2.8 on 2025-11-14 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_doctor_departments_doctor_symptoms_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorAppointmentFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('General', 'General Consultation'), ('FollowUp', 'Follow-up'), ('Telemedicine', 'Telemedicine'), ('Special', 'Special Consultation')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_fees', to='doctor.doctor')),
            ],
            options={
                'unique_together': {('doctor', 'category')},
            },
        ),
    ]
