# Generated by Django 5.2.8 on 2025-12-06 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_alter_doctorappointmentfee_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='total_reviews',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
