# Generated by Django 5.2.8 on 2025-11-09 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptom',
            name='symptom_image',
            field=models.ImageField(blank=True, null=True, upload_to='symptoms/'),
        ),
    ]
