# Generated by Django 5.2.8 on 2025-11-10 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_alter_symptom_symptom_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department_image',
            field=models.ImageField(blank=True, null=True, upload_to='department/'),
        ),
    ]
