# Generated by Django 5.2.8 on 2025-11-19 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_doctorappointmentfee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorappointmentfee',
            name='category',
            field=models.CharField(choices=[('General', 'General Consultation'), ('Special', 'Special Consultation')], max_length=50),
        ),
    ]
