# Generated by Django 5.2.8 on 2025-12-21 21:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointment', '0005_alter_appointment_transaction_id'),
        ('core', '0001_initial'),
        ('doctor', '0005_doctor_rating_doctor_total_reviews'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientSymptomLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms_input', models.TextField(help_text="Patient's description of symptoms")),
                ('possible_conditions', models.JSONField(default=list, help_text='List of possible conditions')),
                ('urgency_level', models.CharField(choices=[('emergency', 'Emergency - Need immediate care'), ('urgent', 'Urgent - See doctor within 24 hours'), ('routine', 'Routine - Schedule appointment soon'), ('self_care', 'Self-care - Monitor at home')], max_length=20)),
                ('advice', models.TextField(help_text='General advice for patient')),
                ('confidence_score', models.FloatField(default=0.0, help_text='AI confidence score (0-1)')),
                ('appointment_created', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recommended_departments', models.ManyToManyField(blank=True, to='core.department')),
                ('recommended_doctors', models.ManyToManyField(blank=True, to='doctor.doctor')),
                ('related_appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointment.appointment')),
                ('selected_symptoms', models.ManyToManyField(blank=True, to='core.symptom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptom_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SymptomRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urgency_score', models.IntegerField(default=1, help_text='1-10, higher = more urgent')),
                ('common_conditions', models.JSONField(default=list)),
                ('red_flags', models.TextField(blank=True, help_text='Warning signs that need emergency care')),
                ('self_care_tips', models.TextField(blank=True)),
                ('related_departments', models.ManyToManyField(to='core.department')),
                ('symptom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.symptom')),
            ],
            options={
                'ordering': ['symptom__name'],
            },
        ),
    ]
